### ISSUE TITLE
error[E0464]: multiple matching crates for `cargo_check_bug`

### ISSUE THREAD

**Issue by colin-kiegel** [colin-kiegel/cargo_check_bug#1]
# Steps to reprodroduce

1. `git clone https://github.com/colin-kiegel/cargo_check_bug.git`
2. `cd cargo_check_bug`
3. `rustup override set nightly-2017-03-03`
4. `cargo clean && cargo test && cargo check`
5. `cargo clean && cargo check && cargo test`

Result:
Step 4: Everything OK!
Step 5: ```error[E0464]: multiple matching crates for `cargo_check_bug` ```

## `Cargo.toml`

```toml
[package]
name = "cargo_check_bug"
version = "0.1.0"
build = "build.rs"

[dependencies]

[build-dependencies]
skeptic = "0.6"

[dev-dependencies]
skeptic = "0.6"
```

## `build.rs`

```rust
extern crate skeptic;

fn main() {
    skeptic::generate_doc_tests(&["README.md"]);
}
```

## `README.md`

<pre>
```rust
extern crate cargo_check_bug;

fn main() {
}
```
</pre>

## `tests/skeptic.rs`

```rust
include!(concat!(env!("OUT_DIR"), "/skeptic-tests.rs"));
```

## `src/lib.rs`

(empty)
